package service;

import model.*;
import requests.*;
import results.*;
import chess.ChessGame.TeamColor;

import java.util.Collection;

public class ChessService {

    // Autogenerated comments

    /**
     * Clears all data from the database
     * 
     * @return Empty result indicating success
     */
    public void clear() {
        return;
    }

    /**
     * Registers a new user
     * 
     * @param request Registration information
     * @return Registration result with auth token
     */
    public RegisterResult register(RegisterRequest request) {
        
        return new RegisterResult("Test", "test");
    }

    /**
     * Logs in an existing user
     * 
     * @param request Login credentials
     * @return Login result with auth token
     */
    public LoginResult login(LoginRequest request) {
        return new LoginResult("Test", "test");
    }

    /**
     * Logs out a user
     * 
     * @param authToken User's auth token
     * @return Logout result
     */
    public LogoutResult logout(LogoutRequest request) {
        return new LogoutResult();
    }

    /**
     * Lists all games
     * 
     * @param authToken User's auth token
     * @return List of games
     */
    public ListResult listAll(ListRequest request) {
        return null;
        // return new ListResult();
    }

    /**
     * Creates a new game
     * 
     * @param request   Game creation data
     * @param authToken User's auth token
     * @return Game creation result with game ID
     */
    public NewGameResult newGame(NewGameRequest request) {
        return new NewGameResult("Test");
    }

    /**
     * Joins an existing game
     * 
     * @param request   Game join information
     * @param authToken User's auth token
     * @return Join game result
     */
    public JoinResult joinGame(JoinRequest request) {
        return new JoinResult(TeamColor.BLACK, "Test");
    }
}