version: '3.8'
services:
  app:
    image: mcr.microsoft.com/devcontainers/java:1-21-bullseye
    volumes:
      - ..:/workspaces/chess:cached
    command: sleep infinity
    network_mode: service:db
    depends_on:
      - db
  
  db:
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=javauser
      - MYSQL_PASSWORD=javapassword

volumes:
  mysql-data:
